#!/usr/bin/env python3
"""
Generate (and optionally push) the Kaggle submission notebook.

Wraps submission/attack.py into a notebook that follows the steps in
docs/kaggle_submission_guide.md: install aicomp-sdk, %%writefile attack.py,
validate, optional smoke test. Run scripts/build_submission.py first so
submission/attack.py is up to date.

Usage:
    python scripts/build_notebook.py                # write .ipynb only
    python scripts/build_notebook.py --push          # write + kaggle kernels push
"""

import argparse
import json
from pathlib import Path

ROOT = Path(__file__).resolve().parent.parent
ATTACK_PY = ROOT / "submission" / "attack.py"
NOTEBOOK_DIR = ROOT / "submission" / "notebook"
NOTEBOOK_PATH = NOTEBOOK_DIR / "attack-submission.ipynb"
KERNEL_METADATA_PATH = NOTEBOOK_DIR / "kernel-metadata.json"

KAGGLE_USERNAME = "ayushsingh7863"
# New baseline kernel, replacing jed-redteam-attack-submission (14 versions
# of submission-mechanics debugging history) as the one we actively develop
# against going forward. That original kernel is left alone - it holds the
# first successful "Submit to Competition" run.
KERNEL_SLUG = "jed-redteam-baseline"
COMPETITION_SLUG = "ai-agent-security-multi-step-tool-attacks"
AICOMP_SDK_VERSION = "3.1.2"


def code_cell(source: str) -> dict:
    lines = source.splitlines(keepends=True)
    return {
        "cell_type": "code",
        "execution_count": None,
        "metadata": {},
        "outputs": [],
        "source": lines,
    }


def markdown_cell(source: str) -> dict:
    return {
        "cell_type": "markdown",
        "metadata": {},
        "source": source.splitlines(keepends=True),
    }


def build_notebook(attack_source: str) -> dict:
    writefile_cell = "%%writefile attack.py\n" + attack_source

    cells = [
        markdown_cell(
            "# JED red-team attack submission\n\n"
            "Auto-generated by `scripts/build_notebook.py` from "
            "`submission/attack.py`. Do not edit this notebook by hand — "
            "edit `src/jed_redteam/attack.py` and rebuild.\n\n"
            "After this notebook finishes running (Save & Run All), open "
            "the output page and click **Submit to Competition**."
        ),
        code_cell(writefile_cell),
        # The `aicomp` console script isn't reliably on PATH inside Kaggle's
        # notebook shell after a pip install, so call the CLI's main()
        # in-process instead of relying on the `aicomp` entry-point script.
        code_cell(
            "import sys\n"
            "from aicomp_sdk.cli.main import main as aicomp_main\n\n"
            "sys.argv = ['aicomp', 'validate', 'redteam', 'attack.py']\n"
            "aicomp_main()\n"
        ),
        code_cell(
            "# Optional smoke test before using a real submission slot.\n"
            "sys.argv = ['aicomp', 'test', 'redteam', 'attack.py', "
            "'--budget-s', '60', '--agent', 'deterministic']\n"
            "aicomp_main()\n"
        ),
        markdown_cell(
            "## Register with the evaluation harness\n\n"
            "Two things confirmed necessary via other competitors' working "
            "public submissions (mccocoful/thread 736246): "
            "`JEDAttackInferenceServer().serve()` must be gated behind "
            "`KAGGLE_IS_COMPETITION_RERUN` (calling it unconditionally, as "
            "the official starter notebook does, hangs the commit "
            "indefinitely - it only returns during the real graded rerun). "
            "Separately, Kaggle's \"Submit to Competition\" precondition "
            "check requires a `submission.csv` to already exist in the "
            "committed output *before* the real gateway ever runs, even "
            "though the real per-model scores only exist after a "
            "successful graded rerun - so we write a placeholder "
            "(`Id,Score` rows, all zero) whenever this is not the real "
            "rerun, purely to satisfy that precondition check."
        ),
        code_cell(
            "import os\n"
            "import kaggle_evaluation.jed_attack_134815.jed_attack_inference_server as attack_srv\n\n"
            "if os.getenv('KAGGLE_IS_COMPETITION_RERUN'):\n"
            "    attack_srv.JEDAttackInferenceServer().serve()\n"
            "else:\n"
            "    import csv\n\n"
            "    with open('/kaggle/working/submission.csv', 'w', newline='') as fh:\n"
            "        w = csv.writer(fh)\n"
            "        w.writerow(['Id', 'Score'])\n"
            "        w.writerows([\n"
            "            ['gpt_oss_public', 0.0],\n"
            "            ['gpt_oss_private', 0.0],\n"
            "            ['gemma_public', 0.0],\n"
            "            ['gemma_private', 0.0],\n"
            "        ])\n"
            "    print('Not a competition rerun - wrote placeholder submission.csv.')\n"
        ),
    ]

    return {
        "cells": cells,
        "metadata": {
            "kernelspec": {
                "display_name": "Python 3",
                "language": "python",
                "name": "python3",
            },
            "language_info": {"name": "python", "version": "3.11"},
        },
        "nbformat": 4,
        "nbformat_minor": 5,
    }


def build_kernel_metadata() -> dict:
    return {
        "id": f"{KAGGLE_USERNAME}/{KERNEL_SLUG}",
        "title": "jed-redteam baseline",
        "code_file": NOTEBOOK_PATH.name,
        "language": "python",
        "kernel_type": "notebook",
        "is_private": True,
        # CPU-only: our attack.py doesn't run local inference, so GPU is
        # unnecessary compute (confirmed by another competitor on the
        # forum, thread 736246 - kaggle_evaluation's real grading connects
        # to a separate inference machine, not this kernel's hardware).
        # Also sidesteps GPU-type availability issues entirely (Kaggle
        # assigned an unavailable P100 instead of T4 when this was left on
        # a generic "true", with no way to pin the accelerator type via
        # this metadata schema).
        "enable_gpu": False,
        # The graded submission rerun runs with internet disabled (standard
        # for kernels-only code competitions, and matches the official
        # starter's isInternetEnabled: false); matching that here means we
        # see install/mount problems locally instead of only at submit time.
        "enable_internet": False,
        "competition_sources": [COMPETITION_SLUG],
        "dataset_sources": [],
        "kernel_sources": [],
        "model_sources": [],
    }


def main() -> None:
    parser = argparse.ArgumentParser(description=__doc__)
    parser.add_argument(
        "--push",
        action="store_true",
        help="Run 'kaggle kernels push' after generating the notebook.",
    )
    args = parser.parse_args()

    if not ATTACK_PY.exists():
        raise SystemExit(
            f"{ATTACK_PY.relative_to(ROOT)} not found — run "
            "scripts/build_submission.py first."
        )

    attack_source = ATTACK_PY.read_text()

    NOTEBOOK_DIR.mkdir(parents=True, exist_ok=True)
    NOTEBOOK_PATH.write_text(json.dumps(build_notebook(attack_source), indent=1))
    print(f"Wrote {NOTEBOOK_PATH.relative_to(ROOT)}")

    KERNEL_METADATA_PATH.write_text(json.dumps(build_kernel_metadata(), indent=2))
    print(f"Wrote {KERNEL_METADATA_PATH.relative_to(ROOT)}")

    if args.push:
        import subprocess

        subprocess.run(
            ["kaggle", "kernels", "push", "-p", str(NOTEBOOK_DIR)],
            check=True,
        )


if __name__ == "__main__":
    main()
