#!/usr/bin/env python3
"""
Bundle src/jed_redteam/attack.py into submission/attack.py.

Kaggle's code-competition harness only accepts a single flat attack.py with
no local package imports, so real development happens in src/jed_redteam
(a proper importable package) and this script strips it down to one file
before each Kaggle push.

Usage:
    python scripts/build_submission.py
"""

import re
from pathlib import Path

ROOT = Path(__file__).resolve().parent.parent
SRC = ROOT / "src" / "jed_redteam" / "attack.py"
OUT = ROOT / "submission" / "attack.py"

HEADER = '''"""
AI Agent Security Competition - Attack Submission

Auto-generated by scripts/build_submission.py from src/jed_redteam/attack.py.
Do not edit this file directly - edit the source and rebuild.
"""

'''


def build() -> None:
    source = SRC.read_text()

    # Drop the module docstring from the source file; HEADER replaces it.
    source = re.sub(r'^""".*?"""\n\n?', "", source, count=1, flags=re.DOTALL)

    OUT.write_text(HEADER + source)
    print(f"Built {OUT.relative_to(ROOT)} from {SRC.relative_to(ROOT)} ({len(source)} bytes)")


if __name__ == "__main__":
    build()
